replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/terraform-project-uckunski/nodejs/nodejs
  pullPolicy: IfNotPresent
  tag: "3.0.0"

ingress:
  enabled: true
  annotations: 
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: dev-nodejs.hasanuckun.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: nodejs-dev-tls
     hosts:
       - dev-nodejs.hasanuckun.com